application: thegearru
version: live
runtime: python
api_version: 1

default_expiration: 14d 

derived_file_type:
- python_precompiled


skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 )$


handlers:

- url: /.*\.(css|js)
  script: minifier.py

- url: /(robots.txt|favicon.ico|yandex_7fa8a064ec105a1b.html)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico|yandex_7fa8a064ec105a1b.html)

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: deferred.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*

- url: /.*
  script: static.py


#inbound_services:
#- warmup
